from .base import Method, MethodPrediction  # noqa: F401
from .factory import build_method, method_names, register_method  # noqa: F401
from .sage_ds import (  # noqa: F401
    ALL_TOPO,
    Controller,
    HardConcreteGate,
    SageDSMethod,
    project_aux,
    params_reached_by_aux,
    selective_utility,
)
from .sage_ds_v2 import (  # noqa: F401
    SageDSV2Method,
    bilevel_utilities,
    cosine_utility,
    support_fraction,
)
from .sage_ds_v3 import (  # noqa: F401
    AmortizedAllocationSolver,
    SageDSV3Method,
    class_balanced_meta_batch,
    qp_certificate,
    qp_kkt_residual,
    robust_selective_target,
    solve_sage_v3_qp,
)
from .sage_topk import (  # noqa: F401
    SageTopKMethod,
    LinearAuxHead,
    allocation_certificate,
    classification_compatible_direction,
    normalize_direction,
    select_topk_sites,
    solve_topk_allocation,
)
from .depthfrag import (  # noqa: F401
    DepthFragMethod,
    FragHead,
    FragProbe,
    GradNormAccumulator,
    params_reached_by_probes,
    probe_gradient_report,
)
from .depthfrag_v2 import (  # noqa: F401
    DepthFragV2Method,
    whitened_rho,
    teacher_whitened_targets,
    iterative_boundary_distance,
    compute_boundary_direction,
    run_oracle_diagnostic,
)
from .riskflow import (  # noqa: F401
    InputAdapter,
    RiskCell,
    RiskFlowMethod,
    RiskFlowTrace,
    decorrelation_penalty,
    pool_tap,
)
from .riskflow_v2 import (  # noqa: F401
    InnovationCell,
    RiskFlowV2Method,
    RiskFlowV2Trace,
    SoftCell,
    _soft_target,
)
from .scsf import (  # noqa: F401
    MODES,
    SCSFMethod,
    MetaCalibrator,
    meta_weight_cosine,
)
from .scsf_correctness import SCSFCorrectnessMethod  # noqa: F401
from .dtr_scsf import DTRProbe, DTRSCSFMethod  # noqa: F401
from .scores import (  # noqa: F401
    SCORE_FUNCS,
    compute_scores,
    energy,
    entropy,
    logit_margin,
    msp,
    negative_entropy,
    tcp,
)

__all__ = [
    "Method",
    "MethodPrediction",
    "build_method",
    "register_method",
    "method_names",
    "SageDSMethod",
    "SageDSV2Method",
    "SageDSV3Method",
    "SageTopKMethod",
    "LinearAuxHead",
    "solve_topk_allocation",
    "allocation_certificate",
    "select_topk_sites",
    "normalize_direction",
    "classification_compatible_direction",
    "solve_sage_v3_qp",
    "qp_certificate",
    "qp_kkt_residual",
    "robust_selective_target",
    "class_balanced_meta_batch",
    "AmortizedAllocationSolver",
    "bilevel_utilities",
    "cosine_utility",
    "support_fraction",
    "HardConcreteGate",
    "Controller",
    "project_aux",
    "params_reached_by_aux",
    "selective_utility",
    "ALL_TOPO",
    "DepthFragMethod",
    "FragProbe",
    "FragHead",
    "GradNormAccumulator",
    "params_reached_by_probes",
    "probe_gradient_report",
    "RiskFlowMethod",
    "RiskCell",
    "InputAdapter",
    "RiskFlowTrace",
    "decorrelation_penalty",
    "pool_tap",
    "RiskFlowV2Method",
    "RiskFlowV2Trace",
    "InnovationCell",
    "SoftCell",
    "_soft_target",
    "SCSFCorrectnessMethod",
    "DTRProbe",
    "DTRSCSFMethod",
    "msp",
    "entropy",
    "negative_entropy",
    "energy",
    "logit_margin",
    "tcp",
    "compute_scores",
    "SCORE_FUNCS",
]